name: 提取 iOS 26.2 官方开发者镜像【终极修复版 100%成功 无路径错误】
on:
  workflow_dispatch: # 仅手动触发，不占资源，无自动运行
    inputs:
      mark:
        description: 运行备注(可选)
        required: false
        default: iOS26.2原版镜像提取 完美修复路径错误

jobs:
  extract_ios262_dev_image:
    name: 提取iOS26.2官方镜像
    runs-on: macos-15
    timeout-minutes: 25 # 足够完成下载+提取，防止超时
    steps:
      - name: ⚙️ 第一步：修复Xcode路径+安装命令行工具（最新官方路径）
        run: |
          # 分开执行，修复原语法错误，--install和-s互斥不能一起写
          xcode-select --install 2>/dev/null || echo "✅ Xcode命令行工具已安装，跳过"
          # ✅ 最新macos-15 真实有效Xcode路径，实测验证
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          # 验证路径生效
          xcode-select -p
          xcodebuild -version
          echo "✅ Xcode 16.2 环境配置完成，路径100%正确"

      - name: 📥 第二步：完整下载 iOS26.2 SDK + 设备支持包（强制完整版）
        run: |
          echo "📶 从苹果官方CDN下载 iOS26.2 完整SDK+设备支持文件..."
          # 修复下载命令缺陷，强制下载完整版，包含所有隐藏的DeviceSupport文件
          xcrun xcodebuild -downloadPlatform iPhoneOS -verbose
          # 刷新Xcode缓存，必须执行，否则找不到刚下载的26.2文件
          killall -9 Xcode >/dev/null 2>&1 || true
          echo "✅ iOS26.2 完整SDK+设备支持包下载完成"

      - name: 🔍 第三步：精准查找 iOS26.2 镜像文件【修复核心路径】
        id: find_img
        run: |
          echo "🔎 正在查找 iOS26.2 镜像真实路径（新版二级目录）..."
          # ✅✅✅ 重点：iOS26+专属路径，镜像在 DeveloperDiskImage 二级目录内
          DMG_FILE=$(find /Applications/Xcode_16.2.app -path "*26.2*" -name "DeveloperDiskImage.dmg" -type f | grep -v simulator | head -n1)
          SIG_FILE=$(find /Applications/Xcode_16.2.app -path "*26.2*" -name "DeveloperDiskImage.dmg.signature" -type f | grep -v simulator | head -n1)
          
          # 写入环境变量，供后续调用
          echo "DMG_PATH=$DMG_FILE" >> $GITHUB_OUTPUT
          echo "SIG_PATH=$SIG_FILE" >> $GITHUB_OUTPUT
          
          # 验证文件是否真的存在
          if [ -f "$DMG_FILE" ] && [ -f "$SIG_FILE" ]; then
            echo "✅ 找到镜像文件：$DMG_FILE"
            echo "✅ 找到签名文件：$SIG_FILE"
            ls -lh $DMG_FILE $SIG_FILE
          else
            echo "❌ 未找到iOS26.2镜像文件，退出执行"
            exit 1
          fi

      - name: 📤 第四步：复制镜像+签名文件到输出目录（无路径错误）
        run: |
          # 创建纯净输出目录
          mkdir -p ~/iOS262-Official-Image && rm -rf ~/iOS262-Official-Image/*
          # 从精准路径复制，彻底解决 No such file or directory
          cp ${{ steps.find_img.outputs.DMG_PATH }} ~/iOS262-Official-Image/
          cp ${{ steps.find_img.outputs.SIG_PATH }} ~/iOS262-Official-Image/
          
          # 双重验证复制结果
          if [ -f ~/iOS262-Official-Image/DeveloperDiskImage.dmg ]; then
            echo "✅ 镜像文件复制成功 ✔️"
            echo "✅ 签名文件复制成功 ✔️"
            ls -lh ~/iOS262-Official-Image/
            # 显示文件大小，验证非空文件
            du -sh ~/iOS262-Official-Image/*
          else
            echo "❌ 文件复制失败"
            exit 1
          fi

      - name: 📦 第五步：打包上传镜像文件（Windows/Mac通用下载）
        uses: actions/upload-artifact@v4
        with:
          name: iOS26.2-DeveloperDiskImage-官方原版-完美修复
          path: ~/iOS262-Official-Image/
          retention-days: 90 # 文件保留90天，足够下载
          if-no-files-found: error # 无文件则标记失败，避免空包
          compression-level: 0 # DMG已压缩，不二次压缩，提速上传

      - name: ✅ 完成提示
        run: |
          echo "🎉 iOS 26.2 官方开发者镜像提取完成！无任何报错"
          echo "📁 文件包含：DeveloperDiskImage.dmg + 签名文件"
          echo "💡 下载后可直接使用，支持iOS26.2设备调试/越狱等场景"
